name: Get and Cache Dependencies
description: Get the dependencies and cache them
inputs:
  caching:
    description: Whether to cache dependencies or not
    required: false
    default: 'true'
outputs:
  used-cache:
    description: Whether the cache was used
    value: ${{ steps.install.cache }}
runs: 
  using: composite
  steps:
    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v2
      with:
        # path: ~/.cache/pip
        path: ${{ env.pythonLocation }}
        # key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
        key:  ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

    - name: 'Install Dependencies'
      id: install
      if : steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        pip install -r requirements.txt
        echo "cache=${{inputs.caching}}" >> $GITHUB_OUTPUT
      shell: bash