name: Get and Cache Dependencies
description: Get the dependencies and cache them
runs: 
  using: composite
  steps:
    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v2
      with:
        # path: ~/.cache/pip
        path: ${{ env.pythonLocation }}
        # key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
        key:  ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

    - name: 'Install Dependencies'
      if : steps.cache.outputs.cache-hit != 'true'
      run: pip install -r requirements.txt
      shell: bash