name: Matrix Jobs
on: push
jobs:
  deploy:
      name: Dummy Deploy
      continue-on-error: true 
      strategy: 
        matrix: 
          python-version: ['3.10', '3.11']
          operating-system: [ubuntu-latest]
      runs-on: ${{ matrix.operating-system }}
      steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install Dependencies
          run: pip install -r requirements.txt
        - name: Print Message
          run: echo '${{ toJson(github) }}'