name: Matrix Jobs
on: push
jobs:
  deploy:
      name: Dummy Deploy
      strategy: 
        matrix: 
          python-version: [8,9]
          operating-system: [ubuntu-latest, windows-latest]
      runs-on: '${{ matrix.operating-system }}'
      steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: Install Python
          uses: actions/setup-python@v4
            with:
              python-version: '${{ matrix.python-version }}'
        - name: Install Dependencies
          run: pip install requirements.txt
        - name: Print Message
          run: echo '${{ toJson(github) }}'