name: Continuos Integration Workflow


on:
  pull_request:
    branches:
      - main

defaults:
  run: 
    shell: bash


jobs:

  test:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'

    - name: 'Install Dependencies'
      run: pip install -r requirements.txt

    - name: 'Run Testes'
      run: pytest -vv


