name: Continuos Integration Workflow


on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
      
  pull_request:
    types:
      - closed
    branches:
      - main

defaults:
  run: 
    shell: bash


jobs:

  test:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  

    - name: 'Install Dependencies'
      run: pip install -r requirements.txt

    - name: 'Run Tests'
      run: pytest -vv

  lint:
    name: 'Run Linting'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Linting
      run: pylint ./simple_python/simple_python.py

  test-job:
    needs: [lint, test]
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hellow World!"
      - name: Print Goodbye
        run: echo "Done - Bye"


