name: Continuos Integration Workflow


on:
  workflow_dispatch:
  push:
    branches:
      - main
      
  # pull_request:
  #   types:
  #     - opened
  #   branches:
  #     - main
    # paths-ignore:
    #   - '.github/workflows/*'

defaults:
  run: 
    shell: bash


jobs:

  test:
    name: 'Run unit tests wow'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

    - name: 'Install Dependencies'
      run: pip install -r requirements.txt

    - name: 'Run Tests'
      run: pytest -vv

  lint:
    name: 'Run Linting'
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'

    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Linting
      run: pylint ./simple_python/simple_python.py

    - name: Build package
      run: python setup.py sdist bdist_wheel

    - name: Publish Wheel file name
      id: publish
      run: find dist/*.whl -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'

    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: dist-files
        path: |
            dist 

  deploy:
    name: Deploy Job
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output Contents
        run: ls
      - name: Output filename
        run: echo "${{ needs.lint.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying..."
  

  


